name: ebuildtester
base: core20
version: '0.1.30'
summary: Tool to test a Gentoo ebuild and its dependencies
description: |
    This script is a tool to test a Gentoo ebuild and its dependencies. The
    idea is that the package is emerged in a clean (and current) stage3 Docker
    container.
grade: stable
confinement: strict

apps:
  ebuildtester:
    command: bin/ebuildtester
    plugs:
      - docker

parts:
  ebuildtester:
    plugin: python
    source: https://github.com/nicolasbock/ebuildtester.git
    source-type: git
    source-tag: v0.1.30
    requirements:
      - requirements.txt
